import numpy as np 
a1 = np.array([ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ])
print(a1)
print(type(a1))
print(a1.dtype)
print(a1.shape)
print(a1.ndim)
print(a1.size)
print(a1[0])
a2 = np.array([[[],[]],[[],[]],[[],[]]])
print(a2)
print(type(a2))
print(a2.dtype)
print(a2.shape)
print(a2.ndim)
print(a2.size)
print(a2[0])